version: '3'

services: 

  app:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - message_broker

  message_broker:
    image: rabbitmq:3.8.11-management
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"